import assert from "node:assert/strict";
import { algebraModes, buildRequest, draftKeyFor, initialForm, validateResults } from "../src/quantum/model.js";
const form = initialForm();
const request = buildRequest(form);
assert.equal(request.script.variableAssignments, form.variableAssignments);
assert.equal(request.script.multivectorsVisualized, ":psi;");
assert.equal(request.algebraDimension, 2);
assert.equal(request.visualizationEnabled, true);
assert.deepEqual(request.optimization, { cse: false, maxima: false });
form.outputMode = "CODE_ONLY";
assert.equal(buildRequest(form).visualizationEnabled, false);
assert.equal(buildRequest(form).script.variableAssignments, form.variableAssignments);
const state = { nqubits: 2, labels: ["00", "01", "10", "11"], real: [1, 0, 0, 0], imaginary: [0, 0, 0, 0], probabilities: [1, 0, 0, 0], totalProbability: 1, residualNorm: 0 };
assert.deepEqual(validateResults({ psi: state }, 2), { psi: state });
assert.deepEqual(validateResults({}, 2), {});
assert.throws(() => validateResults(undefined, 2));
assert.throws(() => validateResults({ psi: state }, 3));
assert.throws(() => validateResults({ psi: { ...state, probabilities: [NaN, 0, 0, 0] } }, 2));
console.log("Quantum request and result validation passed.");
for (const mode of ["QGA"]) {
  const draft = initialForm(mode);
  draft.outputMode = "CODE_AND_VISUALIZATION";
  draft.variableAssignments = "scale=2;";
  draft.multivectorsVisualized = ":scaled;";
  const request = buildRequest(draft, mode);
  assert.equal(request.algebraPlugins, `ALGEBRA_${mode}`);
  assert.equal(request.outputMode, "CODE_ONLY");
  assert.equal(request.visualizationEnabled, false);
  assert.equal(request.script.variableAssignments, "");
  assert.equal(request.script.multivectorsVisualized, "");
  assert.notEqual(draftKeyFor(mode), draftKeyFor("QRA"));
  if (mode === "QGA") assert.equal("algebraDimension" in request, false);
}
assert.deepEqual(algebraModes.QCA.dimensions, [1, 2, 3]);
assert.deepEqual(algebraModes.QGA.dimensions, []);
assert.notEqual(draftKeyFor("QCA"), draftKeyFor("QGA"));
const qca = buildRequest(initialForm("QCA"), "QCA");
assert.equal(qca.visualizationEnabled, true);
assert.equal(qca.script.multivectorsVisualized, ":psi;");
assert.ok(qca.script.variableAssignments.includes("theta"));
assert.equal(algebraModes.QCA.numeric, false);
console.log("QCA and Q bit GA capability and draft isolation checks passed.");
